name: Add profile credentials to ~/.aws/credentials
description: 'adding profile to eb cli'
runs:
  using: "composite"
  steps:
    - run: |
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile eb-cli
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile eb-cli
        aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile eb-cli
      shell: bash
